name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Install X11/OpenGL
      run: sudo apt-get update && sudo apt-get install -y xorg-dev

    - name: Set up Go 1.18
      uses: actions/setup-go@v4
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Install Fyne tools
      run: make install-fyne && make install-fyne-cross

    - name: Tests
      run: make test
  
    - name: Build test binaries
      run: PATH=${PATH}:~/go/bin make .build-test-binaries
